chreipl: impove disk type detection when running under QEMU
ibm-s390-linux/s390-tools pull request #154
Opened 2023-08-23 13:28 UTC by nikita-dubrovskii

User can attach disk with smth like: "-device virtio-scsi-ccw,... -device scsi-hd,...", so virtio block device appears as '/dev/sda' instead of '/dev/vda'. chreipl assumes all '/dev/sd*' disks as FCP disks, which is not a case in such setup.

2023-08-23 13:29 UTC, nikita-dubrovskii commented
This fixes an issue: https://github.com/coreos/fedora-coreos-tracker/issues/1434

2023-09-13 13:35 UTC, borntraeger commented
I think this makes sense.

2023-09-28 07:27 UTC, mhartmay commented
Does this work if `virtio-scsi-pci` is used for the SCSI controller?
E.g.
`-device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x1`

I'm asking because I suspect it doesn't.  Here's the result of the realpath command executed in a guest using `virtio-scsi-pci`:
```
root@qemus390x:~# realpath /sys/block/sda/device
/sys/devices/pci0001:00/0001:00:00.0/virtio2/host0/target0:0:2/0:0:2:0
```

So the statement `strstr(resolved, "virtio") != NULL)` [1] would also evaluate to true, but the type is obviously not CCW.

If `virtio-scsi-ccw` is used the result of realpath is:
```
root@qemus390x:~# realpath /sys/block/sda/device
/sys/devices/css0/0.0.0000/0.0.0003/virtio0/host0/target0
```

[1] https://github.com/ibm-s390-linux/s390-tools/pull/154/files#diff-77c5828a786983ff0a5792636002c1aec766c63abb578610798c2c10bc4abc1bR400

2023-09-28 12:17 UTC, nikita-dubrovskii commented
@mhartmay thx for the observation! Indeed it won't work with `virtio-scsi-pci` :
```
$ realpath /sys/block/sda/device
/sys/devices/pci0001:00/0001:00:00.0/virtio0/host0/target0:0:0/0:0:0:0

$ chreipl /dev/sda
chreipl: Could not lookup device number for "sda"
```

2023-10-05 08:36 UTC, mhartmay commented
Code itself looks correct, but could you please refactor some parts of it? 
E.g. this part
```
snprintf(path, sizeof(path), "/sys/block/%s/device", dev_name);
if (realpath(path, resolved) == NULL)
		return -1;
```
is similar to
https://github.com/ibm-s390-linux/s390-tools/blob/master/ipl_tools/ccw.c#L83

In addition something similar to `sscanf` (e.g. https://github.com/ibm-s390-linux/s390-tools/blob/master/ipl_tools/ccw.c#L92) reads better than the `strstr()` construct.

2023-10-12 14:12 UTC, nikita-dubrovskii commented
@mhartmay Done

2023-10-13 06:51 UTC, mhartmay commented on ipl_tools/cmd_chreipl.c
> +
This change seems to be unrelated.

2023-10-13 07:12 UTC, mhartmay commented on ipl_tools/cmd_chreipl.c
> +	    ccw_busid_get_sysfs_new(dev_name, busid) == 0)
Unfortunately, I think this breaks list-directed IPL from ECKD DASD support. One fix would be to change the order... First check for `(strncmp(dev_name, "eckd", strlen("eckd")) == 0)
		l.reipl_type = REIPL_ECKD;` and then the checks dasd, vd etc...

@svens-s390

2023-10-13 07:18 UTC, mhartmay commented on ipl_tools/cmd_chreipl.c
> +	    ccw_busid_get_sysfs_new(dev_name, busid) == 0)
Secondly, do we need to consider `ccw_busid_get_sysfs_old` as well? Next possible issue, is the array length of bussid large enough? Do we need to protect against a buggy kernel?  I don't think it's a problem - but just mention it to get a second opinion.

2023-10-13 12:22 UTC, nikita-dubrovskii commented on ipl_tools/cmd_chreipl.c
> +	    ccw_busid_get_sysfs_new(dev_name, busid) == 0)
Now it becomes more complicated, because we  have to rely on `if ()` order, maybe it's better to use previous solution with `realpath ; strstr(virtio) && strstr(css)` ? I mean it's not a refactoring anymore, but some kind of breaking change

2023-10-13 13:37 UTC, mhartmay commented on ipl_tools/ccw.c
> +
Hmm let's Sven decide if he likes this construct or not - I guess for two places I would leave it open-coded.

2023-10-13 13:44 UTC, mhartmay commented on ipl_tools/ccw.c
> +	if (sscanf(path, "/sys/devices/css0/%*[0-9a-f.]/%*[0-9a-f.]/virtio%d", &virtio) != 1)
```suggestion
	size_t virtio_num;

	REALPATH(device, path);

	/*
	 * The output has the following format:
	 * /sys/devices/css0/0.0.0000/0.0.0000/virtio0/block/vda
	 */
	if (sscanf(path, "/sys/devices/css0/%*[0-9a-f.]/%*[0-9a-f.]/virtio%zu", &virtio_num) != 1)
```

2023-10-13 13:49 UTC, mhartmay commented on ipl_tools/ccw.c
> +
...and if `buf[PATH_MAX]` instead of `buf[4096]` is okay or not.

2023-10-13 13:52 UTC, nikita-dubrovskii commented on ipl_tools/ccw.c
> +
Should be:
```
$ man -s3 realpath
...
If resolved_path is specified as NULL, then realpath() uses malloc(3) to allocate a buffer
of up to PATH_MAX bytes to hold the resolved pathname, and returns a pointer to this buffer.  
```

2023-10-30 10:07 UTC, nikita-dubrovskii commented
@mhartmay so, does PR now look ok?

2023-11-30 09:01 UTC, steffen-eiden commented on ipl_tools/ccw.c
> +
I'd prefer a more precise name for this macro: `REALPATH_BLOCK` for example.
Also, this could be a helper function instead of a macro.
`int realpath_block(const char* device, char* path)`

In any case please add a short description of what that function or macro does/

The compiler then will decide if it makes more sense to inline the function or not.

2023-11-30 12:13 UTC, nikita-dubrovskii commented on ipl_tools/ccw.c
> +
Done, but i prefer macro in this case. Making a function would require more checks and probably memory allocation

2023-12-19 08:38 UTC, hoeppnerj requested changes
Hi @nikita-dubrovskii a couple more review comments from my side.

Also, please limit the commit message to lines to 72 characters. Our [editorconfig](https://github.com/ibm-s390-linux/s390-tools/blob/27708026d41006d8432a265d40c3c524c4047bf5/.editorconfig#L33) defines this limit too, please consider using it.

2023-12-19 08:38 UTC, hoeppnerj commented on ipl_tools/ccw.c
> +                if (realpath(buf, (path)) == NULL)                            \
I wonder if it would make sense to put `realpath()` into `util_path_sysfs()` in general and then you wouldn't need this macro here. However, that needs some testing and maybe a bit more thoughts to not break other users.

2023-12-19 08:38 UTC, hoeppnerj commented on ipl_tools/ccw.c
> +	if (sscanf(path, "/sys/devices/css0/%*[0-9a-f.]/%[0-9a-f.]", busid) != 1)
Couldn't this function just call `util_sys_get_dev_addr()`?

https://github.com/ibm-s390-linux/s390-tools/blob/27708026d41006d8432a265d40c3c524c4047bf5/libutil/util_sys.c#L138

2023-12-19 08:38 UTC, hoeppnerj commented on ipl_tools/ccw.c
> +
Please use tabs for indentation.

2023-12-19 08:38 UTC, hoeppnerj commented on ipl_tools/ccw.c
> +	if (sscanf(path, "/sys/devices/css0/%*[0-9a-f.]/%*[0-9a-f.]/virtio%zu", &virtio) != 1)
Considering my comment regarding testing, this makes it hard to test due to the hardcoded `/sys` path. However, just skipping `/sys` (using e.g. `strstr()`) wouldn't do the trick. We'd need a util sscanf() function that takes `SYSFS_ROOT` into account. Nothing you should do now. I just wanted to share my thoughts on it.

2023-12-19 08:38 UTC, hoeppnerj commented on ipl_tools/ccw.c
> +	size_t virtio = 0;
Why are you using `size_t`? Shouldn't `unsinged int` be sufficient? `size_t` is typically used for count of bytes. It's a little confusing for this temporary variable here.

2024-02-05 12:21 UTC, nikita-dubrovskii commented on ipl_tools/ccw.c
> +	size_t virtio = 0;
`size_t` is an `unsigned int`. I'm just used to it, cause lot of `stdlib` functions return `size_t/ssize_t`

2024-02-05 12:23 UTC, nikita-dubrovskii commented on ipl_tools/ccw.c
> +	if (sscanf(path, "/sys/devices/css0/%*[0-9a-f.]/%[0-9a-f.]", busid) != 1)
Hmm, don't think so. `util_sys_get_dev_addr` would be overhead here, and existing code in this source file also uses `sscanf`. I don't want to make a refactoring here.

2024-02-05 12:27 UTC, nikita-dubrovskii commented on ipl_tools/ccw.c
> +                if (realpath(buf, (path)) == NULL)                            \
Done.  I guess changing of `util_path_sysfs` shouldn't be part of this PR, as its purpose is just to fix `virtio` block devices detection.

2024-03-12 16:36 UTC, mhartmay commented on ipl_tools/ccw.c
> +		buf = util_path_sysfs("block/%s/device", (device));                                \
```suggestion
		char *buf = util_path_sysfs("block/%s/device", (device));                                \
```

2024-03-13 10:11 UTC, mhartmay commented on ipl_tools/ccw.c
> +static char *device_sysfs_path(const char *device, char *path, size_t path_size)
Please don't return `char *`, because people might think they have to free the returned value. Instead, add to the documentation that path must be PATH_MAX large and the value will be replaced in place.

And please use `const size_t path_size`.

2024-03-13 15:23 UTC, mhartmay commented
LGTM. Acked-by: Marc Hartmayer <mhartmay@linux.ibm.com>

But someone more familiar with CSS/CCW should look at the functions names and documentation.

2024-03-19 09:17 UTC, hbrueckner commented on ipl_tools/ccw.c
> +	assert(device);
I wonder whether `util_assert` should be used instead

2024-03-19 09:39 UTC, nikita-dubrovskii commented on ipl_tools/ccw.c
> +	assert(device);
Done

2024-05-03 23:51 UTC, dustymabe commented
anything still blocking this?

2024-05-15 14:51 UTC, hoeppnerj commented
Pulled and integrated, will be pushed to master soon. Thanks!

2024-05-27 15:03 UTC, closed without merging