correct mapping of ATTESTATION_NR when uvdevice doesn't support info IOCTL
ibm-s390-linux/s390-tools pull request #163
Opened 2024-03-13 17:08 UTC by VasiliyS

UvDevice::ATTESTATION_NR was used to set the supported uv commands as a value directly, which led to *bit* 0 being set.

As a result, the library (UvDeviceInfo via Display)  reported that `Info` was supported.

2024-03-13 17:17 UTC, steffen-eiden requested changes
Good catch, thanks for providing  fix.

Beside the little nit LGTM

2024-03-13 17:17 UTC, steffen-eiden commented on rust/pv_core/src/uvdevice/info.rs
> +            let mut supp_uvio_cmds : Lsb0Flags64 = 0u64.into();
I'd prefer 
`let mut supp_uvio_cmds = Lsb0Flags64::default();`

2024-03-14 15:22 UTC, steffen-eiden requested changes
Some additional nits regarding the commit message.

Could you add a short patch note what you are fixing.

also add a `Signed-off by: <Your Name> email` statement at the end of the commit message,

2024-03-17 15:14 UTC, VasiliyS commented on rust/pv_core/src/uvdevice/info.rs
> +            let mut supp_uvio_cmds : Lsb0Flags64 = 0u64.into();
Ok, will do.

2024-03-18 13:50 UTC, steffen-eiden commented
Thank you for fixing the issue.

I will pick the patches, squash them and publish with the next wave of up-stream update.

2024-03-18 13:52 UTC, steffen-eiden approved these changes

2024-03-22 11:17 UTC, closed without merging